#include "ai_animation_observer.hpp"
#include "ai_animation_metadata.hpp"
#include "damage_native.hpp"
#include "character_native.hpp"
#include "runtime_options.hpp"
#include "world_runtime.hpp"
#include <vector>
#include <array>
#include <cstdio>
#include <cstring>
namespace ai_animation {
namespace {
uintptr_t module=0;unsigned hits[49]{},sequence=0;uint64_t deadline=0;LONG ownerThread=0;
struct Record {uint32_t returned=0,owner=0,request=0,parent=0,clock=0,wholeSequence=0,role=0;bool selected=false;std::array<uint8_t,112> model{};std::array<uint8_t,232> actor{};std::vector<uint8_t> records;std::array<uint32_t,9> regs{};alignas(16) std::array<uint8_t,544> fp{};};
thread_local std::vector<Record> stack;
void*ptr(uint32_t v){return reinterpret_cast<void*>(uintptr_t(v));}
uint32_t word(const void*p){return damage::word(p);}
bool readable(uint32_t v,unsigned n){return character::native::readable(ptr(v),n);}
bool string(uint32_t p,const char*match=nullptr){for(unsigned i=0;i<256;++i){if(!readable(p+i,1))return false;char c=*static_cast<char*>(ptr(p+i));if(match && c!=match[i])return false;if(!c)return true;}return false;}
bool model(uint32_t address,std::array<uint8_t,112>&bytes,std::vector<uint8_t>&records){if(!readable(address,112))return false;std::memcpy(bytes.data(),ptr(address),112);const uint32_t count=word(bytes.data()+40),begin=word(bytes.data()+88),end=word(bytes.data()+92),capacity=word(bytes.data()+96);if(count<1 || count>256 || !begin || end<begin || capacity<end || (end-begin)%272 || (capacity-begin)%272 || (end-begin)/272<count || (end-begin)/272>256 || !readable(begin,end-begin))return false;for(uint32_t i=0;i<count;++i)if(!string(begin+272*i))return false;records.resize(end-begin);std::memcpy(records.data(),ptr(begin),records.size());return true;}
void hex(FILE*f,const void*p,unsigned n){std::fputc('"',f);const auto*b=static_cast<const uint8_t*>(p);for(unsigned i=0;i<n;++i)std::fprintf(f,"%02x",b[i]);std::fputc('"',f);}
void save(const Record&r,const uint32_t*frame,const uint8_t*fp){char dir[384]{},path[512];GetEnvironmentVariableA("OPENBOXER_AI_CAPTURE_DIR",dir,sizeof(dir));std::snprintf(path,sizeof(path),"%s/ai-selector-original-%03u.json",dir,++sequence);FILE*f=std::fopen(path,"wb");if(!f)return;const auto&role=aiAnimationRoles[r.role];std::array<uint8_t,112> after{};std::vector<uint8_t> records;const bool safe=model(uint32_t(module+role.model),after,records);std::fprintf(f,"{\"format\":\"GAME-0003-selector-observer-v1\",\"observation_only\":true,\"candidate\":false,\"original_forward_count\":1,\"original_body_rva\":28224,\"module\":%u,\"process\":%lu,\"thread\":%lu,\"tick_ms\":%llu,\"sequence\":%u,\"whole_exit_sequence\":%u,\"owner\":%u,\"requested_pointer\":%u,\"requested_name\":\"%s\",\"caller\":%u,\"parent_ebp\":%u,\"parent_j\":1,\"variant\":%u,\"desired_state\":%u,\"remembered_state\":%u,\"type\":%u,\"eax\":%u,\"entry_clock_raw32\":%u,\"exit_clock_raw32\":%u,\"post_shape_safe\":%s,\"entry_regs36\":",unsigned(module),GetCurrentProcessId(),GetCurrentThreadId(),static_cast<unsigned long long>(GetTickCount64()),sequence,r.wholeSequence,r.owner,r.request,role.name,r.returned,r.parent,role.variant,role.state,role.state,role.type,frame[7],r.clock,word(ptr(uint32_t(module+0x17d904))),safe?"true":"false");hex(f,r.regs.data(),36);std::fputs(",\"exit_regs36\":",f);hex(f,frame,36);std::fputs(",\"entry_fp544\":",f);hex(f,r.fp.data(),544);std::fputs(",\"exit_fp544\":",f);alignas(16) std::array<uint8_t,544> exitFp{};std::memcpy(exitFp.data(),fp,540);hex(f,exitFp.data(),544);std::fputs(",\"entry_model112\":",f);hex(f,r.model.data(),112);std::fputs(",\"exit_model112\":",f);hex(f,after.data(),112);std::fputs(",\"entry_actor232\":",f);hex(f,r.actor.data(),232);std::fputs(",\"exit_actor232\":",f);hex(f,ptr(uint32_t(module+0x1849f8)),232);std::fputs(",\"entry_records\":",f);hex(f,r.records.data(),unsigned(r.records.size()));std::fputs(",\"exit_records\":",f);hex(f,records.data(),unsigned(records.size()));std::fprintf(f,",\"post_variant\":%u,\"post_desired_state\":%u,\"post_remembered_state\":%u}\n",word(ptr(uint32_t(module+0x184788))),word(ptr(uint32_t(module+0x184a9c))),word(ptr(uint32_t(module+0x184a98))));std::fclose(f);}
}
extern "C" uint32_t ai_selector_before(uint32_t*frame,uint8_t*fp){Record r;r.returned=frame[10];r.owner=frame[6];r.request=frame[11];r.parent=frame[2];const LONG thread=LONG(GetCurrentThreadId());if(stack.empty() && (!deadline || GetTickCount64()<deadline))for(unsigned i=0;i<(damage::continuationCaptureRequested()?49u:42u);++i){const auto&t=aiAnimationRoles[i];if(t.state==0 && !damage::latestContinuationCompletionSequence())continue;if(hits[i]>=2 || r.returned!=module+t.returned || r.owner!=module+t.owner || r.request!=module+t.literal)continue;if(r.parent<24 || !readable(r.parent-24,4) || word(ptr(r.parent-24))!=1 || word(ptr(uint32_t(module+0x184788)))!=t.variant || word(ptr(uint32_t(module+0x184a9c)))!=t.state || word(ptr(uint32_t(module+0x184a98)))!=t.state || !string(r.request,t.name))continue;if(ownerThread!=thread && InterlockedCompareExchange(&ownerThread,thread,0)!=0)continue;if(!model(uint32_t(module+t.model),r.model,r.records))continue;r.selected=true;r.role=i;r.clock=word(ptr(uint32_t(module+0x17d904)));r.wholeSequence=damage::latestAiSequence();std::memcpy(r.actor.data(),ptr(uint32_t(module+0x1849f8)),232);std::memcpy(r.regs.data(),frame,36);std::memcpy(r.fp.data(),fp,540);++hits[i];if(!deadline)deadline=GetTickCount64()+45000;break;}stack.push_back(std::move(r));return uint32_t(module+0x6e40);}
extern "C" uint32_t ai_selector_return(uint32_t*frame,uint8_t*fp){Record r=std::move(stack.back());stack.pop_back();if(r.selected)save(r,frame,fp);return r.returned;}
extern "C" void ai_selector_entry();
bool install(uintptr_t base){if(!damage::aiCaptureRequested())return true;if(!runtime_options::original(runtime_options::Unit::Clip))return false;char dir[384]{};GetEnvironmentVariableA("OPENBOXER_AI_CAPTURE_DIR",dir,sizeof(dir));if(!dir[0] || base!=0x400000)return false;module=base;auto direct=[&](uint32_t rva,uint32_t target,uint8_t opcode){if(!readable(uint32_t(base+rva),5))return false;auto*p=static_cast<uint8_t*>(ptr(uint32_t(base+rva)));return p[0]==opcode && uint32_t(base+rva+5+int32_t(word(p+1)))==base+target;};if(!direct(0x1c26,0x6e40,0xe9))return false;for(unsigned i=0;i<(damage::continuationCaptureRequested()?49u:42u);++i)if(!direct(aiAnimationRoles[i].call,0x1c26,0xe8))return false;return world::redirect(base+0x1c26,uintptr_t(&ai_selector_entry));}
}
