set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_C_COMPILER C:/msys64/ucrt64/bin/clang.exe)
set(CMAKE_CXX_COMPILER C:/msys64/ucrt64/bin/clang++.exe)
set(CMAKE_ASM_COMPILER C:/msys64/ucrt64/bin/clang.exe)
set(CMAKE_C_COMPILER_TARGET i686-w64-windows-gnu)
set(CMAKE_CXX_COMPILER_TARGET i686-w64-windows-gnu)
set(CMAKE_ASM_COMPILER_TARGET i686-w64-windows-gnu)
set(CMAKE_SYSROOT C:/msys64/mingw32)
set(CMAKE_C_FLAGS_INIT "-B C:/msys64/mingw32/bin")
set(CMAKE_CXX_FLAGS_INIT "-B C:/msys64/mingw32/bin")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libgcc -static-libstdc++")
