"""Agent3 observable checkpoint oracle. No original implementation consulted.

Input: {"cases": [{"label": str, "count": int,
"sortInputRecords": [[uint32]*14]*3, "postSortRecords": same,
"postWaveRecords": same, "selected": {"positions": [[uint32]*3]*3,
"colors": same, "directions": same, "parameters": [uint32]*3}}]}.
Record inputs are captured AFTER scoring/rotation. Wave state must be captured
independently; this oracle does not invent opaque dependency behavior.
"""
import argparse
import json
import math
import struct
from pathlib import Path


def scalar(word):
    if not isinstance(word, int) or not 0 <= word <= 0xffffffff:
        raise ValueError("record fields require unsigned raw 32-bit words")
    return struct.unpack('<f', struct.pack('<I', word))[0]


def records(value):
    if len(value) != 3 or any(len(row) != 14 for row in value):
        raise ValueError("checkpoint must contain exactly three complete records")
    for row in value:
        for word in row:
            scalar(word)
    return [list(row) for row in value]


def ordered_checkpoint(source, count):
    result = records(source)
    if not isinstance(count, int) or count > 3 or count <= -0x80000000:
        raise ValueError("count outside approved isolated oracle scope")
    if any(not math.isfinite(scalar(row[11])) for row in result[:max(count, 0)]):
        raise ValueError("special distance values require expanded FP evidence")
    # Contract-defined exchange order, with identity-bearing complete records.
    for earlier in range(max(0, count - 1)):
        for later in range(earlier + 1, count):
            if scalar(result[earlier][11]) > scalar(result[later][11]):
                incoming = result[later]
                displaced = result[earlier]
                displaced[9] = 0x00000007
                result[earlier], result[later] = incoming, displaced
    return result


def published_checkpoint(after_wave):
    rows = records(after_wave)
    return {
        'positions': [row[0:3] for row in rows],
        'colors': [[0x3f800000] * 3 for _ in rows],
        'directions': [row[6:9] for row in rows],
        'parameters': [row[9] for row in rows],
    }


def word(value):
    return struct.unpack('<I', struct.pack('<f', value))[0]


def self_check():
    # Independently derived identity/parameter vectors; these expected answers
    # are literal, not generated by the ordering function under test.
    vectors = [([2, 2, 1], [3, 2, 1], [103, 102, 7]),
               ([3, 2, 1], [3, 2, 1], [103, 7, 7]),
               ([2, 3, 1], [3, 1, 2], [103, 7, 7]),
               ([1, 2, 3], [1, 2, 3], [101, 102, 103])]
    for distances, identities, parameters in vectors:
        source = [[(tag << 16) + field for field in range(14)]
                  for tag in (1, 2, 3)]
        for index, distance in enumerate(distances):
            source[index][0] = index + 1
            source[index][9] = 101 + index
            source[index][11] = word(distance)
        actual = ordered_checkpoint(source, 3)
        assert [row[0] for row in actual] == identities
        assert [row[9] for row in actual] == parameters
    sentinel = [[tag * 100 + field for field in range(14)] for tag in (1, 2, 3)]
    for count in (-3, 0, 1):
        assert ordered_checkpoint(sentinel, count) == sentinel
    publication = published_checkpoint(sentinel)
    assert publication['positions'] == [[100, 101, 102], [200, 201, 202], [300, 301, 302]]
    assert publication['directions'] == [[106, 107, 108], [206, 207, 208], [306, 307, 308]]
    assert publication['parameters'] == [109, 209, 309]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('input', nargs='?', type=Path)
    arguments = parser.parse_args()
    self_check()
    if arguments.input is None:
        print('Oracle self-check PASS; original/candidate validation not performed.')
        return
    cases = json.loads(arguments.input.read_text(encoding='utf-8-sig'))['cases']
    failures, blocked = [], []
    for index, case in enumerate(cases):
        label = case.get('label', str(index))
        try:
            expected_sort = ordered_checkpoint(case['sortInputRecords'], case['count'])
            if records(case['postSortRecords']) != expected_sort:
                failures.append({'label': label, 'category': 'FAIL_STATE', 'checkpoint': 'ordering'})
            expected_publication = published_checkpoint(case['postWaveRecords'])
            if case['selected'] != expected_publication:
                failures.append({'label': label, 'category': 'FAIL_STATE', 'checkpoint': 'publication'})
        except (KeyError, ValueError, TypeError) as error:
            blocked.append({'label': label, 'reason': str(error)})
    result = 'FAIL' if failures else 'BLOCKED' if blocked or not cases else 'PASS'
    print(json.dumps({'result': result, 'scope': 'ordering/publication checkpoints only',
                      'cases': len(cases), 'failures': failures, 'blocked': blocked}, indent=2))
    raise SystemExit(0 if result == 'PASS' else 1)


if __name__ == '__main__':
    main()
